create sequence hibernate_sequence start 1 increment 1;

create table travel_note
(
    id        int8 generated by default as identity,
    name_note varchar(2048) not null,
    filename  varchar(255),
    note      varchar(2048) not null,
    user_id   int8,
    primary key (id)
);

create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);

create table usr
(
    id              int8 generated by default as identity,
    activation_code varchar(255),
    email           varchar(255) not null,
    is_active       boolean      not null,
    password        varchar(255) not null,
    username        varchar(255) not null,
    primary key (id)
);

create table country
(
    id   int8 generated by default as identity,
    name varchar(255) not null,
    code varchar(255) not null UNIQUE,
    primary key (id, code)
);

create table city
(
    id           int8 generated by default as identity,
    name         varchar(255) not null,
    code         varchar(255) not null,
    country_code varchar(255) not null references country (code),
    primary key (id)
);

create table flight_ticket
(
    id                    int8 generated by default as identity,
    price                 int8         not null,
    origin_city_code      varchar(255) not null,
    number_of_changes     int4         not null,
    duration              int8         not null,
    distance              int8         not null,
    destination_city_code varchar(255) not null,
    departure_date        timestamp    not null,
    is_actual             boolean      not null,
    travel_note_id        int8,
    city_of_depart_id     int8,
    country_of_depart_id  int8,
    city_arrive_id        int8,
    country_arrive_id     int8,
    primary key (id)
);

alter table if exists travel_note
    add constraint travel_note_user_fk
        foreign key (user_id) references usr;

alter table if exists user_role
    add constraint user_role_user_fk
        foreign key (user_id) references usr;
